spring.application.name=BookStore-APIGateway

server.port=8090


# Enable discovery from Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route for Book Service
spring.cloud.gateway.routes[0].id=book-service-route
spring.cloud.gateway.routes[0].uri=lb://bookstore-bookservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/books/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Route for Order Service
spring.cloud.gateway.routes[1].id=order-service-route
spring.cloud.gateway.routes[1].uri=lb://bookstore-orderservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
